import { colors } from '@/constants/colors';
import {
  AppNotification,
  Application,
  Conversation,
  Job,
  Message,
  MessageRequest,
  User,
} from '@/types';

/**
 * Bundled demo dataset. Mirrors the Figma reference content so every screen is
 * populated with real, distinct copy (no lorem ipsum, no duplicated text).
 * Used when EXPO_PUBLIC_USE_MOCK is enabled.
 */

export const mockUsers: Record<string, User> = {
  u_brian: {
    id: 'u_brian',
    name: 'Brian Kamau',
    email: 'brian@gmail.com',
    role: 'freelancer',
    roles: ['freelancer'],
    title: 'Cinematographer',
    city: 'Nairobi',
    avatarColor: colors.avatarRed,
    availability: 'available',
    rating: 4.8,
    reviewCount: 24,
    skills: ['Canon C300', 'DaVinci', 'Lighting', 'Gimbals'],
    credits: [
      { id: 'c1', project: 'Mali — Feature Film', role: 'DOP', year: 2023 },
      { id: 'c2', project: 'Safaricom Ad', role: 'Camera Op', year: 2024 },
      { id: 'c3', project: 'NTV Documentary', role: 'Cinematographer', year: 2024 },
    ],
    dayRate: 8000,
    status: 'active',
  },
  u_amina: {
    id: 'u_amina',
    name: 'Amina Mwangi',
    email: 'amina@gmail.com',
    role: 'freelancer',
    roles: ['freelancer'],
    title: 'Sound Engineer',
    city: 'Mombasa',
    avatarColor: colors.avatarBlue,
    availability: 'on_project',
    rating: 4.6,
    reviewCount: 18,
    skills: ['Boom Op', 'Sound Devices', 'Mixing', 'ADR'],
    credits: [
      { id: 'c1', project: 'Kovu — Short Film', role: 'Sound Recordist', year: 2024 },
      { id: 'c2', project: 'KCB Brand Film', role: 'Sound Mixer', year: 2023 },
    ],
    dayRate: 5000,
    status: 'active',
  },
  u_james: {
    id: 'u_james',
    name: 'James Otieno',
    email: 'james@gmail.com',
    role: 'freelancer',
    roles: ['freelancer'],
    title: 'Video Editor',
    city: 'Nairobi',
    avatarColor: colors.avatarGreen,
    availability: 'available',
    rating: 4.9,
    reviewCount: 31,
    skills: ['Premiere Pro', 'After Effects', 'Colour Grading', 'Motion'],
    credits: [
      { id: 'c1', project: 'Tusker Promo', role: 'Lead Editor', year: 2024 },
      { id: 'c2', project: 'Crime & Justice S2', role: 'Offline Editor', year: 2023 },
    ],
    dayRate: 6500,
    status: 'suspended',
  },
  u_faith: {
    id: 'u_faith',
    name: 'Faith Wanjiku',
    email: 'faith@gmail.com',
    role: 'freelancer',
    roles: ['freelancer'],
    title: 'Makeup Artist',
    city: 'Nairobi',
    avatarColor: colors.avatarPurple,
    availability: 'available',
    rating: 5.0,
    reviewCount: 12,
    skills: ['SFX Makeup', 'Beauty', 'Prosthetics', 'Period Looks'],
    credits: [
      { id: 'c1', project: 'Sultana S3', role: 'Key Makeup', year: 2024 },
      { id: 'c2', project: 'Coke Studio Africa', role: 'Makeup Artist', year: 2023 },
    ],
    dayRate: 4500,
    status: 'active',
  },
  p_kamau: {
    id: 'p_kamau',
    name: 'Kamau Productions',
    email: 'studio@kamau.co.ke',
    role: 'producer',
    roles: ['producer'],
    title: 'Feature & commercial production house',
    city: 'Nairobi',
    avatarColor: colors.avatarGreen,
    rating: 4.9,
    reviewCount: 40,
    jobsPosted: 12,
    status: 'active',
  },
  p_nairobi: {
    id: 'p_nairobi',
    name: 'Nairobi Films Ltd',
    email: 'hello@nairobifilms.co.ke',
    role: 'producer',
    roles: ['producer'],
    title: 'Documentary & TV production',
    city: 'Nairobi',
    avatarColor: colors.avatarPurple,
    rating: 4.7,
    reviewCount: 22,
    jobsPosted: 8,
    status: 'active',
  },
};

export const mockJobs: Job[] = [
  {
    id: 'job_dop',
    title: 'DOP Needed',
    category: 'Camera',
    department: 'Camera',
    productionType: 'Feature Film',
    location: 'Nairobi, Kenya',
    startDate: 'Jul 10',
    endDate: 'Jul 15, 2025',
    dayRate: 8000,
    description:
      'Feature film seeking experienced DOP with 5+ years experience on Canon cinema cameras. Must have strong knowledge of colour grading and lighting for night interiors.',
    status: 'open',
    applicationCount: 8,
    shortlistedCount: 3,
    producer: {
      id: 'p_kamau',
      name: 'Kamau Productions',
      jobsPosted: 12,
      rating: 4.9,
      avatarColor: colors.avatarGreen,
    },
    postedAt: '2025-06-20T09:00:00Z',
  },
  {
    id: 'job_sound',
    title: 'Sound Recordist',
    category: 'Sound',
    department: 'Sound',
    productionType: 'Commercial',
    location: 'Mombasa, Kenya',
    startDate: 'Jul 20',
    endDate: 'Jul 22, 2025',
    dayRate: 5000,
    description:
      'Commercial shoot, 2 days BTS sound. Looking for a recordist with their own boom and recorder kit. Coastal travel and accommodation covered.',
    status: 'open',
    applicationCount: 15,
    shortlistedCount: 0,
    producer: {
      id: 'p_nairobi',
      name: 'Nairobi Films Ltd',
      jobsPosted: 8,
      rating: 4.7,
      avatarColor: colors.avatarPurple,
    },
    postedAt: '2025-06-18T11:30:00Z',
  },
  {
    id: 'job_editor',
    title: 'Offline Editor',
    category: 'Edit',
    department: 'Editing',
    productionType: 'Documentary',
    location: 'Nairobi, Kenya',
    startDate: 'Aug 1',
    endDate: 'Aug 30, 2025',
    dayRate: 6500,
    description:
      'Long-form documentary needs an offline editor for a month-long cut. Premiere Pro workflow, proxy media supplied. Story-driven editors preferred.',
    status: 'open',
    applicationCount: 6,
    shortlistedCount: 2,
    producer: {
      id: 'p_kamau',
      name: 'Kamau Productions',
      jobsPosted: 12,
      rating: 4.9,
      avatarColor: colors.avatarGreen,
    },
    postedAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'job_gaffer',
    title: 'Gaffer',
    category: 'Lighting',
    department: 'Lighting',
    productionType: 'TV Series',
    location: 'Nakuru, Kenya',
    startDate: 'Sep 5',
    endDate: 'Sep 20, 2025',
    dayRate: 5500,
    description:
      'TV drama series seeking a gaffer experienced with LED fixtures and generator power. Two-week block, possible extension for season two.',
    status: 'open',
    applicationCount: 4,
    shortlistedCount: 1,
    producer: {
      id: 'p_nairobi',
      name: 'Nairobi Films Ltd',
      jobsPosted: 8,
      rating: 4.7,
      avatarColor: colors.avatarPurple,
    },
    postedAt: '2025-06-12T14:00:00Z',
  },
  {
    id: 'job_actor',
    title: 'Lead Actor (Male, 30s)',
    category: 'Acting',
    department: 'Acting',
    productionType: 'Short Film',
    location: 'Nairobi, Kenya',
    startDate: 'Jul 28',
    endDate: 'Jul 30, 2025',
    dayRate: 7000,
    description:
      'Award-bound short film casting a male lead in his thirties, fluent in Swahili and English. Emotionally demanding role; theatre background a plus.',
    status: 'open',
    applicationCount: 21,
    shortlistedCount: 5,
    producer: {
      id: 'p_kamau',
      name: 'Kamau Productions',
      jobsPosted: 12,
      rating: 4.9,
      avatarColor: colors.avatarGreen,
    },
    postedAt: '2025-06-10T10:00:00Z',
  },
];

/** Producer's own jobs (Producer Home → My Jobs). */
export const mockProducerJobs: Job[] = [
  mockJobs[0],
  {
    ...mockJobs[1],
    title: 'Sound Recordist',
    productionType: 'Documentary',
    status: 'closed',
    applicationCount: 15,
    shortlistedCount: 0,
  },
  {
    id: 'job_makeup',
    title: 'Makeup Artist',
    category: 'Acting',
    department: 'Makeup',
    productionType: 'Short Film',
    location: 'Nairobi, Kenya',
    startDate: 'Aug 1',
    endDate: 'Aug 3, 2025',
    dayRate: 4500,
    description:
      'Short film needs a makeup artist for a three-day shoot, including one light SFX wound. Kit provided for prosthetics.',
    status: 'open',
    applicationCount: 3,
    shortlistedCount: 3,
    producer: {
      id: 'p_kamau',
      name: 'Kamau Productions',
      jobsPosted: 12,
      rating: 4.9,
      avatarColor: colors.avatarGreen,
    },
    postedAt: '2025-06-19T09:00:00Z',
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app_1',
    jobId: 'job_dop',
    status: 'shortlisted',
    coverLetter:
      'I have extensive experience with Canon cinema cameras and my own full equipment kit available, including a C300 Mk III and a set of CP.2 primes.',
    applicant: {
      id: 'u_brian',
      name: 'Brian Kamau',
      title: 'Cinematographer',
      rating: 4.8,
      avatarColor: colors.avatarRed,
    },
  },
  {
    id: 'app_2',
    jobId: 'job_dop',
    status: 'pending',
    coverLetter:
      'I recently shot a feature on the Coast and would love to bring that low-light, handheld energy to your project. References available on request.',
    applicant: {
      id: 'u_amina',
      name: 'Amina Mwangi',
      title: 'DOP',
      rating: 4.6,
      avatarColor: colors.avatarBlue,
    },
  },
  {
    id: 'app_3',
    jobId: 'job_dop',
    status: 'declined',
    coverLetter:
      'Camera operator with eight years on commercials and music videos. I am comfortable operating gimbal and Steadicam for fast-paced shoots.',
    applicant: {
      id: 'u_james',
      name: 'James Otieno',
      title: 'Camera Op',
      rating: 4.5,
      avatarColor: colors.avatarGreen,
    },
  },
  {
    id: 'app_4',
    jobId: 'job_dop',
    status: 'shortlisted',
    coverLetter:
      'My reel is built around natural-light drama and documentary. I grade my own DaVinci projects, so you get a consistent look from set to delivery.',
    applicant: {
      id: 'u_faith',
      name: 'Faith Wanjiku',
      title: 'Cinematographer',
      rating: 5.0,
      avatarColor: colors.avatarPurple,
    },
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv_kamau',
    participantId: 'p_kamau',
    participantName: 'Kamau Productions',
    avatarColor: colors.avatarGreen,
    lastMessage: 'Are you available for the shoot on Jul 10?',
    timestamp: '2m',
    unread: true,
    online: true,
  },
  {
    id: 'conv_nairobi',
    participantId: 'p_nairobi',
    participantName: 'Nairobi Films',
    avatarColor: colors.avatarPurple,
    lastMessage: "Great, let's confirm the call time",
    timestamp: '1h',
    unread: true,
    online: false,
  },
  {
    id: 'conv_showbiz',
    participantId: 'p_showbiz',
    participantName: 'Showbiz Kenya',
    avatarColor: colors.avatarOrange,
    lastMessage: "Thanks for applying, we'll be in touch soon",
    timestamp: '3h',
    unread: false,
    online: false,
  },
  {
    id: 'conv_mombasa',
    participantId: 'p_mombasa',
    participantName: 'Mombasa Films',
    avatarColor: colors.avatarBlue,
    lastMessage: 'Hi, are you available for next week?',
    timestamp: '1d',
    unread: false,
    online: false,
  },
];

export const mockMessages: Record<string, Message[]> = {
  conv_kamau: [
    {
      id: 'm1',
      conversationId: 'conv_kamau',
      senderId: 'p_kamau',
      text: 'Hi Brian! Are you available for our feature film shoot Jul 10-15?',
      createdAt: '2025-06-24T09:00:00Z',
      isRead: true,
    },
    {
      id: 'm2',
      conversationId: 'conv_kamau',
      senderId: 'me',
      text: "Hello! Yes, I'm available. What are the details?",
      createdAt: '2025-06-24T09:02:00Z',
      isRead: true,
    },
    {
      id: 'm3',
      conversationId: 'conv_kamau',
      senderId: 'p_kamau',
      text: "It's in Nairobi. Rate is KES 8,000/day. Interested?",
      createdAt: '2025-06-24T09:03:00Z',
      isRead: true,
    },
    {
      id: 'm4',
      conversationId: 'conv_kamau',
      senderId: 'me',
      text: "That works perfectly for me. Let's proceed!",
      createdAt: '2025-06-24T09:05:00Z',
      isRead: true,
    },
  ],
  conv_nairobi: [
    {
      id: 'm1',
      conversationId: 'conv_nairobi',
      senderId: 'p_nairobi',
      text: 'We loved your documentary reel. Can you do a recce next Tuesday?',
      createdAt: '2025-06-24T08:00:00Z',
      isRead: true,
    },
    {
      id: 'm2',
      conversationId: 'conv_nairobi',
      senderId: 'me',
      text: 'Absolutely. Morning works best for me.',
      createdAt: '2025-06-24T08:10:00Z',
      isRead: true,
    },
    {
      id: 'm3',
      conversationId: 'conv_nairobi',
      senderId: 'p_nairobi',
      text: "Great, let's confirm the call time",
      createdAt: '2025-06-24T08:12:00Z',
      isRead: true,
    },
  ],
};

export const mockRequests: MessageRequest[] = [
  {
    id: 'req_kamau',
    fromId: 'p_kamau',
    fromName: 'Kamau Productions',
    fromRole: 'Producer',
    rating: 4.9,
    avatarColor: colors.avatarGreen,
    preview:
      "Hi! We're looking for an experienced DOP for our upcoming feature film project. Are you interested?",
  },
  {
    id: 'req_nairobi',
    fromId: 'p_nairobi',
    fromName: 'Nairobi Films Ltd',
    fromRole: 'Producer',
    rating: 4.7,
    avatarColor: colors.avatarPurple,
    preview:
      'We have a documentary shoot next month and need a skilled cinematographer on board.',
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'n1',
    type: 'message_request',
    title: 'New Message Request',
    subtitle: 'Kamau Productions wants to connect',
    timestamp: '2m ago',
    group: 'today',
    read: false,
    target: '/requests',
  },
  {
    id: 'n2',
    type: 'application_shortlisted',
    title: 'Application Shortlisted',
    subtitle: 'DOP Needed · Nairobi Films',
    timestamp: '1h ago',
    group: 'today',
    read: false,
    target: '/job/job_dop',
  },
  {
    id: 'n3',
    type: 'review_received',
    title: 'New Review Received',
    subtitle: 'Nairobi Films rated you 5 ★',
    timestamp: '3h ago',
    group: 'today',
    read: false,
  },
  {
    id: 'n4',
    type: 'application_sent',
    title: 'Job Application Sent',
    subtitle: 'Sound Recordist · Mombasa',
    timestamp: 'Yesterday',
    group: 'earlier',
    read: true,
    target: '/job/job_sound',
  },
  {
    id: 'n5',
    type: 'profile_viewed',
    title: 'Profile Viewed',
    subtitle: 'Someone viewed your profile',
    timestamp: '2 days ago',
    group: 'earlier',
    read: true,
  },
];

/** The signed-in demo accounts (selected by the role chosen at login). */
export const demoAccounts: Record<'freelancer' | 'producer' | 'admin', User> = {
  freelancer: mockUsers.u_brian,
  producer: mockUsers.p_kamau,
  admin: {
    id: 'admin_root',
    name: 'Platform Admin',
    email: 'admin@cineconnect.ke',
    role: 'admin',
    roles: ['admin'],
    status: 'active',
  },
};
